# Lights Out

In [1]:
import numpy as np
import math

## Exercice 1

Le but de cet exercice est de créer deux fonctions, une qui associe le vecteur colonne dans la base canonique à une matrice de $Mm,n(K)$
et l’autre qui fait l’opération inverse.

### Question 1

Soit $A∈M_{m,n}(K)$ et $V$ le vecteur colonne associé.

- Quelle est la dimension de $V$ ?
- Quelle est la relation entre les $V_k$ et les $A_{i,j}$ ?

> La dimension de $V$ est $mn$.

> $V_k ​= A_{i,j}$ ​où $k = i + (j−1)m$

### Question 2

Écrire une fonction colonne `Vecteur_Colonne(A)` qui prend en entrée une matrice et retourne le vecteur associé de la bonne taille.

In [2]:
# équivalent à mat.flatten(order='F')
def vecteurColonne(mat: np.array) -> np.array :
	"""Retourne le vecteur colonne associé à la matrice."""
	i_max = len(mat)
	j_max = len(mat[0])
	vecSize = i_max * j_max
	vec = np.empty(shape=vecSize, dtype=int, order='F')

	for j in range(j_max):
		for i in range(i_max):
			vec[j * i_max + i] = mat[i][j]

	return vec

In [3]:
mat = np.array([[1, 2, 3], [4, 5, 6]])

print(mat, '\n')
print(vecteurColonne(mat))

[[1 2 3]
 [4 5 6]] 

[1 4 2 5 3 6]


### Question 3

Écrire la fonction `Matrice(V)` qui prend en entrée un vecteur colonne de taille $n^2$ et retourne la matrice de taille $n \times n$ correspondante.

In [4]:
def matrice(vec: np.array) -> np.array or False:
  """
  Retourne la matrice de taille n*n correspondante au vecteur de taille n²,
  ou False si le vecteur n'est pas de la bonne taille.
  """
  n = math.sqrt(len(vec))
  if n.is_integer(): n = int(n)
  else: return False
  
  mat = np.empty(shape=(n,n), dtype=int)
  
  for i in range(n):
    for j in range(n):
      mat[i][j] = vec[j * n + i]
  
  return mat

In [5]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
vec = vecteurColonne(mat)

print(vec, '\n')
print(matrice(vec))

[1 4 7 2 5 8 3 6 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercice 2

Créer une fonction `Croix(i,j,n)` qui crée la matrice $C_{i,j}$ de taille $n^2$ avec des 1 seulement en $(i,j)$
et les voisins verticaux et horizontaux. Il y aura des zéros aux autres positions.

In [6]:
def croix(i: int, j: int, n: int) -> np.array:
  """
  Crée une matrice de taille n² avec des 1 seulement en (i,j) et les
  voisins verticaux et horizontaux. Il y aura des zéros aux autres positions.
  """
  mat = np.zeros(shape=(n,n), dtype=int)
  
  i_min = max(0, i-1)
  j_min = max(0, j-1)
  
  i_max = min(n-1, i+1)
  j_max = min(n-1, j+1)
  
  for a in range(i_min, i_max+1): mat[a][j] = 1
  for a in range(j_min, j_max+1): mat[i][a] = 1
  
  return mat

In [93]:
print(croix(2,2,5), '\n')
print(croix(4,4,5), '\n')
print(croix(0,0,5))

[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 1 1 1 0]
 [0 0 1 0 0]
 [0 0 0 0 0]] 

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 1]] 

[[1 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


## Exercice 3 (Jeu 3X3)

Dans cette question, on veut demande de créer un fonction `Lights_Out()` sans variable
d’entrée qui lance le jeu avec les indications:
1. Phrase d’accueil dans le jeu,
2. Tirage d’une configuration alératoire avec la commande `random.randint()` de **Numpy**,
3. Affichage de la configuration initiale,
4. Demande de la case où le joueur veut jouer
5. Récupération du numéro de ligne et de colonne avec la commande `input()`
6. Mise à jour de la configuration et affichage de celle-ci
7. On continue jusqu’à ce que le joueur éteigne toutes les lampes et dans ce cas, on affiche un message de félicitations et on sort du jeu.



In [94]:
def Lights_Out() -> None:
  def add(mat: np.array, c: np.array) -> np.array:
    size = len(mat)
    for i in range(size):
      for j in range(size):
        mat[i][j] = (mat[i][j] + c[i][j]) % 2
    return mat
  
  moves=0
  n=3
  print("Bienvenue dans Lights Out.")
  mat = np.random.randint(2, size=(n,n))
  
  print("Configuration initiale:\n")
  print(mat)
  
  while np.count_nonzero(mat) > 0:
    print("Veuillez entrer votre prochain coup.")
    i = int(input("Line   >>> "))
    j = int(input("Column >>> "))
    
    c = croix(i,j,n)
    mat = add(mat, c)
    moves += 1
    print(mat, '\n')
  
  print(f"Bravo! Vous avez gagné en {moves} coups.")

In [235]:
Lights_Out()

Bienvenue dans Lights Out.
Configuration initiale:

[[0 0 1]
 [1 1 1]
 [1 1 1]]
Veuillez entrer votre prochain coup.
[[0 0 1]
 [0 1 1]
 [0 0 1]] 

Veuillez entrer votre prochain coup.
[[0 0 0]
 [0 0 0]
 [0 0 0]] 

Bravo! Vous avez gagné en 2 coups.


## Exercice 4 (Matrice de passage)

Créer une fonction `Matrice_Passage(n)` qui prend en entrée la dimension $n$ et retourne la matrice dont les vecteurs
sont les $C_{i,j}$ exprimées dans la base canonique de $M_n(F_2)$.

On prendra les $C_{i,j}$ dans le même ordre que les vecteurs $E_{i,j}$ de la base canonique.


In [82]:
def Matrice_Passage(n: int) -> np.array:
  """
  Retourne la matrice de passage de dimension n
  """
  size = n * n
  M = np.zeros((size, size), dtype=int)

  col = 0
  for j in range(n):
    for i in range(n):
      c = croix(i, j, n)
      v = vecteurColonne(c)
      M[:, col] = v % 2
      col += 1

  return M

In [242]:
MP3 = Matrice_Passage(3)
print("Matrice de passage 3x3:")
print(MP3)

Matrice de passage 3x3:
[[1 1 0 1 0 0 0 0 0]
 [1 1 1 0 1 0 0 0 0]
 [0 1 1 0 0 1 0 0 0]
 [1 0 0 1 1 0 1 0 0]
 [0 1 0 1 1 1 0 1 0]
 [0 0 1 0 1 1 0 0 1]
 [0 0 0 1 0 0 1 1 0]
 [0 0 0 0 1 0 1 1 1]
 [0 0 0 0 0 1 0 1 1]]


## Exercice 5

On veut déterminer pour quelles dimensions, le jeu a toujours une solution.

1. Écrire une boucle qui calcule pour n=2 à 11, le déterminant de `Matrice_Passage(n)`.
  On rappelle que ce déterminant est un nombre dans $F_2$, c’est-à-dire `0` ou `1`. \
  Comme Python fait les calculs avec nombres à virgule flottante, il pourra être utile d’utiliser les commandes `round()`, `int()`
  et ajouter `%2` pour avoir le reste dans la division euclidienne par 2.
2. Donner la liste des dimensions inférieures à 11 pour lesquelles le jeu possède une solution unique pour toute configuration initiale.

In [86]:
def determinant_mod2(mat: np.array) -> int:
  """
  Retourne le déterminant de la matrice dans F2.

  Utilise la fonction numpy.linalg.det pour calculer le déterminant.
  """
  if len(mat) < 2:
    print("La matrice doit être de taille 2x2 minimum.")
    return -1
  elif len(mat) > 11:
    print("La matrice doit être de taille 11x11 maximum.")
    return -1

  det = round(np.linalg.det(mat)) % 2
  return det

In [241]:
print("Matrice de passage 3x3:")
print(MP3)
print("Déterminant:", determinant_mod2(MP3))

Matrice de passage 3x3:
[[1 1 0 1 0 0 0 0 0]
 [1 1 1 0 1 0 0 0 0]
 [0 1 1 0 0 1 0 0 0]
 [1 0 0 1 1 0 1 0 0]
 [0 1 0 1 1 1 0 1 0]
 [0 0 1 0 1 1 0 0 1]
 [0 0 0 1 0 0 1 1 0]
 [0 0 0 0 1 0 1 1 1]
 [0 0 0 0 0 1 0 1 1]]
Déterminant: 1


## Exercice 6 (Inverse de la matrice de passage en dimension 3)

Grâce à Python, calculer l’inverse de la matrice de passage en dimension 3 dans.

On pourra soit faire les calculs dans $R$ avec la commande `linalg.inv()` de Numpy, se ramener aux entiers
puis réduire modulo 2 ou charger le package *Sympy*, changer le type de la matrice avec `Matrix()`
et calculer l’inverse dans $M(F_2)$ avec la méthode `.inv_mod(2)`.

In [ ]:
import sympy as sp

def Matrice_Passage_Inv(n: int) -> np.array:
  """
  Retourne la matrice inverse de passage de dimension n dans F2.
  """
  M = Matrice_Passage(n)
  M_inv = sp.Matrix(M).inv_mod(2)     # matrice sympy inverse % 2
  M_inv = np.array(M_inv)             # on remet en array numpy
  M_inv = M_inv.astype(int)           # on convertit en int
  return M_inv

In [260]:
MP3_inv = Matrice_Passage_Inv(3)
print("Matrice de passage 3x3:")
print(MP3)

print("Matrice de passage inverse 3x3:")
print(MP3_inv)

Matrice de passage 3x3:
[[1 1 0 1 0 0 0 0 0]
 [1 1 1 0 1 0 0 0 0]
 [0 1 1 0 0 1 0 0 0]
 [1 0 0 1 1 0 1 0 0]
 [0 1 0 1 1 1 0 1 0]
 [0 0 1 0 1 1 0 0 1]
 [0 0 0 1 0 0 1 1 0]
 [0 0 0 0 1 0 1 1 1]
 [0 0 0 0 0 1 0 1 1]]
Matrice de passage inverse 3x3:
[[1 0 1 0 0 1 1 1 0]
 [0 0 0 0 1 0 1 1 1]
 [1 0 1 1 0 0 0 1 1]
 [0 0 1 0 1 1 0 0 1]
 [0 1 0 1 1 1 0 1 0]
 [1 0 0 1 1 0 1 0 0]
 [1 1 0 0 0 1 1 0 1]
 [1 1 1 0 1 0 0 0 0]
 [0 1 1 1 0 0 1 0 1]]


## Exercice 7 (Solutionneur en dimension 3)

Écrire une fonction `Solution(A)` qui prend en entrée une configuration initiale
sous forme d’une matrice $3×3 A$ et retourne une matrice solution $S$ (qui contient
des 1 pour les cases où il faut appuyer et des 0 ailleurs).

Tester avec une version en ligne du jeu.

In [ ]:
def Solution(A: np.array) -> np.array:
  """
  Résout la configuration initiale Lights Out A dans F2.
  """
  n = len(A)
  size = n * n
  b = vecteurColonne(A)
  M_inv = Matrice_Passage_Inv(n)

  # Produit de la matrice invcerse et du vecteur colonne de A
  # Source: https://youtu.be/0fHkKcy0x_U?si=MmpyNRYAnp884UF6&t=558
  S = np.dot(M_inv, b) % 2

  return S

In [274]:
A = np.random.randint(2, size=(3,3))
print("Configuration initiale:")
print(A)

S = Solution(A)
print("Matrice solution:")
print(matrice(S))

Configuration initiale:
[[0 1 0]
 [0 1 1]
 [0 1 0]]
Matrice solution:
[[0 0 1]
 [0 0 1]
 [0 0 1]]
